# frozen_string_literal: true

source 'https://rubygems.org'

gem 'sorbet-static-and-runtime'

group :development, :test do
  gem 'awesome_print' # pretty print ruby objects
  gem 'pry' # Console with powerful introspection capabilities
  gem 'pry-byebug', '3.9.0' # Integrates pry with byebug
  # gem 'pry-doc' # Provide MRI Core documentation
  gem 'pry-rescue' # Start a pry session whenever something goes wrong.
  gem 'pry-theme' # An easy way to customize Pry colors via themefiles
end

group :test do
  gem 'rspec', '~> 3.10'
end

gem "rubocop", "~> 1.24"
