# frozen_string_literal: true

source 'https://rubygems.org'

group :development,
      :test do
  gem 'awesome_print' # pretty print ruby objects
  gem 'pry' # Console with powerful introspection capabilities
  gem 'pry-byebug' # Integrates pry with byebug
  gem 'pry-doc' # Provide MRI Core documentation
  gem 'pry-nav', '~> 1.0'
  gem 'pry-rails' # Causes rails console to open pry. `DISABLE_PRY_RAILS=1 rails c` can still open with IRB
  gem 'pry-rescue' # Start a pry session whenever something goes wrong.
  gem 'pry-stack_explorer', '~> 0.6.1'
  gem 'pry-theme' # An easy way to customize Pry colors via themefiles
end

group :test do
  gem 'rspec', '~> 3.10'
end

gem 'rubocop', '~> 1.23'
